// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAPDr9mmUU6bDSbPYdSkVVcfxEQlaeBVM',
    appId: '1:325726111762:web:bd568f9bd30d32142df0cb',
    messagingSenderId: '325726111762',
    projectId: 'employee-management-97d17',
    authDomain: 'employee-management-97d17.firebaseapp.com',
    databaseURL: 'https://employee-management-97d17-default-rtdb.firebaseio.com',
    storageBucket: 'employee-management-97d17.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_w9H62eYnYgnXeMek5D_psVUwUaeG0Tc',
    appId: '1:325726111762:android:61768cfee5227c532df0cb',
    messagingSenderId: '325726111762',
    projectId: 'employee-management-97d17',
    databaseURL: 'https://employee-management-97d17-default-rtdb.firebaseio.com',
    storageBucket: 'employee-management-97d17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNsrCDTBN54mYZ4FekIZNTNZLs2EiNlng',
    appId: '1:325726111762:ios:898d31f55efb6d622df0cb',
    messagingSenderId: '325726111762',
    projectId: 'employee-management-97d17',
    databaseURL: 'https://employee-management-97d17-default-rtdb.firebaseio.com',
    storageBucket: 'employee-management-97d17.firebasestorage.app',
    iosBundleId: 'com.example.employeeManagement',
  );
}
